apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: py4qippk4-python 
  janus-idp.io/tekton: py4qippk4-python
  backstage.io/kubernetes-id: py4qippk4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py4qippk4-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml